services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: formsgworkflow
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: formsgworkflow
      TZ: GMT+8
      PGTZ: GMT+8
    ports:
      - 5432:5432
  temporal:
    image: ghcr.io/miccheng/temporal-dev:latest
    ports:
      - 7233:7233
      - 8233:8233
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - '1080:1080' # Web interface
      - '1025:1025' # SMTP server
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_UI_PORT=1080
    restart: unless-stopped
  mockapi:
    image: mockoon/cli
    volumes:
      - ./mockoon:/data
    ports:
      - 8001:8001
    command: --data /data/mock_api.json --port 8001
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - 'http'
      - '--url=${NGROK_DOMAIN}'
      - 'http://host.docker.internal:3000'
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
