services:
  temporal:
    image: ghcr.io/miccheng/temporal-dev:latest
    ports:
      - 7233:7233
      - 8233:8233
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - 'http'
      - '--url=${NGROK_DOMAIN}'
      - 'http://host.docker.internal:3000'
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
