### Mock Submission

POST https://regular-lucky-coral.ngrok-free.app/api/submissions HTTP/1.1
content-type: application/json

{
    "data": {
        "name": "sample",
        "time": "Wed, 21 Oct 2015 18:27:50 GMT"
    }
}

### Health Check for API endpoint
GET https://regular-lucky-coral.ngrok-free.app/api/submissions

### Health Check for API endpoint (localhost)
GET http://localhost:3000/api/submissions
